- name: Create multiple VM
  hosts: fors1_test
  remote_user: root
  tasks:
    - name: Install zabbix-agent repo
      apt:
        deb: https://repo.zabbix.com/zabbix/5.2/debian/pool/main/z/zabbix-release/zabbix-release_5.2-1+debian10_all.deb

    - name: Install zabbix-agent package
      apt:
        name: zabbix-agent
        state: latest
        update_cache: yes

    - name: Change zabbix-agent config file
      lineinfile:
         path: /etc/zabbix/zabbix_agentd.conf
         regexp: "{{ item.regexp }}"
         line: "{{ item.line }}"
      with_items:
        - { regexp: '^Server=', line: 'Server=YourIP' }
        - { regexp: '^ServerActive=', line: 'ServerActive=YourIP' }
        - { regexp: '^ListenIP=', line: 'ListenIP=YourIP' }
