- name: Create multiple VM
  hosts: localhost
  tasks:
    - name: Login in engine with using user/password
      ovirt_auth:
         url: "url"
         username: user@domen
         password: 'password'
         insecure: yes

    - name: Parse 1vms.csv input file
      read_csv:
           path: 1vms.csv
           key: name
      register: vms
 
    - name: Creates a new Virtual Machine from template
      ovirt_vm:
           auth: "{{ ovirt_auth }}"
           state: present
           name: "{{ item.value.name }}"
           template: debian10
           storage_domain: cephfs_ssd
           cluster: "{{ item.value.cluster }}"
           memory: "{{ item.value.memory }}GiB"
           memory_guaranteed: "{{ item.value.memory_guaranteed }}GiB"
           cpu_cores: "{{ item.value.cpu_cores }}"
           cpu_sockets: "{{ item.value.cpu_sockets }}"
           type: "{{ item.value.class }}"
      loop: "{{ vms.dict|dict2items }}"


    - name: upsize vm's disk.
      ovirt_disk:
         auth: "{{ ovirt_auth }}"
         name: debian-10_Disk1
         vm_name: "{{ item.value.name }}"
         size: "{{ item.value.size }}GiB"
         interface: virtio
         state: present
      loop: "{{ vms.dict|dict2items }}"


    - name: Cloud_init running
      ovirt_vm:
        wait: no
        auth: "{{ ovirt_auth }}"
        state: running
        name: "{{ item.value.name }}"
        cloud_init:
           dns_servers: "{{ item.value.dns1 }} {{ item.value.dns2 }}"
           nic_ip_address: "{{ item.value.ip }}"
           nic_netmask: "{{ item.value.mask }}"
           nic_gateway: "{{ item.value.gw }}"
           nic_name: "{{ item.value.nic }}"
           nic_boot_protocol: static
           nic_on_boot: true
           host_name: "{{ item.value.fqdn }}"
           user_name: root
           root_password: "password"
      loop: "{{ vms.dict|dict2items }}"
